### ISSUE TITLE
SQLTransform stage returning empty outputs when streaming=true

### ISSUE THREAD

**Issue by aissar** [AGLEnergy/arc#18]
When running jobs in streaming mode, the outputs of the SQLTransform stage appear to be empty (i.e. subsequent Load stages result in files with empty records). 

I have run the same job in batch mode without any other changes and the job works as intended (i.e. subsequent Load stages result in files with records).

**Comment by aissar** [comment]
Hi guys,
I managed to find the cause of this issue. It ultimately came down to user error. My input data contained '$' characters within a field assigned as 'double' datatype in my metadata definition. I had previously set this to 'string' so it was never an issue.

For some reason, the TypingTransform stage didn't catch this issue i.e. didn't detect string to double conversion / illegal characters in my input data. So the pipeline kept processing empty rows rather than throwing an exception.

Is the TypingTransform stage supposed to throw an exception if it is unable to convert datatypes?

**Comment by A139834** [comment]
Hi,
The behaviour is that TypingTransform will not throw an error but return null for that value and put an error message into the added _errors array column describing that the field could not be converted. If you set that column to be nullable=false then it will throw an error.

Ill update the docs to clarify.

**Comment by aissar** [comment]
Thank you, that makes sense. Setting nullable=false did throw an exception as expected.
