### ISSUE TITLE
KafkaLoad step completed with 'success' status but messages not loaded to Kafka topic

### ISSUE THREAD

**Issue by aarushissar** [AGLEnergy/arc#2]
Hi there,

I'm testing out the experimental KafkaLoad stage (thank you for incorporating this in the API). I came across the following issue.

Issue: KafkaLoad stage takes long time to run (for only 6 records) and completes with 'success' status; however, the messages are not appearing on the Kafka topic.

See logs below:

{"event":"enter","stage":{"inputView":"outputDFJSON","bootstrapServers":"localhost:29092","acks":-1,"name":"write records to kafka","topic":"foo","type":"KafkaLoad"},"level":"INFO","thread_name":"main","class":"au.com.agl.arc.load.KafkaLoad$","logger_name":"local-1531288592302","timestamp":"2018-07-11 05:56:54.245+0000","environment":"test"}
{"event":"exit","duration":360905,"stage":{"inputView":"outputDFJSON","records":6,"bootstrapServers":"localhost:29092","acks":-1,"numPartitions":1,"name":"write records to kafka","topic":"foo","type":"KafkaLoad"},"level":"INFO","thread_name":"main","class":"au.com.agl.arc.load.KafkaLoad$","logger_name":"local-1531288592302","timestamp":"2018-07-11 06:02:55.150+0000","environment":"test"}
{"event":"exit","status":"success","duration":383617,"level":"INFO","thread_name":"main","class":"au.com.agl.arc.ARC$","logger_name":"local-1531288592302","timestamp":"2018-07-11 06:02:55.152+0000","environment":"test"}

**Comment by A139834** [comment]
Hi,
I have been unable to reproduce. Given that you have acks=-1 (which means all servers must respond) it looks like the messages are being sent to Kafka succesfully.

```bash
docker-compose exec kafka  \
kafka-console-consumer --bootstrap-server localhost:29092 --topic foo --from-beginning 
```

Are you sure you are querying the topic correctly?

I have tested breaking the bootstrapServer (deliberate typo) and it is throwing the correct error:

```json
  "event": "exit",
  "status": "failure",
  "duration": 15870,
  "stage": {
    "inputView": "df",
    "records": 0,
    "bootstrapServers": "locaalhost:29092",
    "acks": -1,
    "numPartitions": 200,
    "name": "df",
    "topic": "foo",
    "messages": [
      "org.apache.spark.SparkException: Job aborted due to stage failure: Task 26 in stage 6.0 failed 1 times, most recent failure: Lost task 26.0 in stage 6.0 (TID 233, localhost, executor driver): org.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:456)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)\n\tat au.com.agl.arc.load.KafkaLoad$$anonfun$load$1.apply(KafkaLoad.scala:86)\n\tat au.com.agl.arc.load.KafkaLoad$$anonfun$load$1.apply(KafkaLoad.scala:66)\n\tat org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)\n\tat org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)\n\tat org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)\n\tat org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)\n\tat org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)\n\tat org.apache.spark.scheduler.Task.run(Task.scala:109)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:405)\n\t... 13 more\n\nDriver stacktrace:",
      "Job aborted due to stage failure: Task 26 in stage 6.0 failed 1 times, most recent failure: Lost task 26.0 in stage 6.0 (TID 233, localhost, executor driver): org.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:456)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)\n\tat au.com.agl.arc.load.KafkaLoad$$anonfun$load$1.apply(KafkaLoad.scala:86)\n\tat au.com.agl.arc.load.KafkaLoad$$anonfun$load$1.apply(KafkaLoad.scala:66)\n\tat org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)\n\tat org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)\n\tat org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)\n\tat org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)\n\tat org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)\n\tat org.apache.spark.scheduler.Task.run(Task.scala:109)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:405)\n\t... 13 more\n\nDriver stacktrace:",
      "Failed to construct kafka producer",
      "No resolvable bootstrap urls given in bootstrap.servers"
    ],
```

can we 100% rule out the Kafka side first?

**Comment by aarushissar** [comment]
Hi Mike,

Thanks for the info above. I'm sure the issue is related to inter container connectivity. I am running Kafka and the Arc framework under separate containers. 

I am able to produce and consume Kafka messages using the console producer and consumer. However, I am having issues when attempting to produce Kafka messages using the Arc framework.

Please see attached files which may assist with trouble shooting:

1) docker-compose.yml (Docker .yml for zookeeper and kafka services)
2) testjob.json (basic ETL stages)
3) start_job.sh (Docker run command for executing the Arc testjob)

[Archive.zip](https://github.com/AGLEnergy/arc/files/2190631/Archive.zip)

**Comment by seddonm1** [comment]
Hi,
Given you are running the Kafka single-node instance docker-compose which is running under `--net host` mode you can also run with `--net host` mode for your Arc container. You may need to add a `--add-host {PUT_YOUR_IP_ADDRESS_HERE}` as for some reason Spark wants to resolve itself. That basically will take away the network isolation that is causing the problem.

Can you please:
1. pull down the latest seddonm1/arc:1.0.8 image as it is currently the `dev` branch and so is changing.
2. confirm that you are getting a stage failure due to network connectivity?

I think this will work:
```bash
docker run \
--net host \
--add-host localhost:$(hostname -I) \
-v $(pwd):${ETL_CONF_BASE_URL} \
-e "ETL_CONF_ENV=test" \
-e "ETL_CONF_BASE_URL=${ETL_CONF_BASE_URL}" \
-it -p 4040:4040 seddonm1/arc:1.0.8 \
bin/spark-submit \
--master local[*] \
--driver-memory=12G \
--driver-java-options="-XX:+UseG1GC -XX:-UseGCOverheadLimit -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap" \
--class au.com.agl.arc.ARC \
/opt/spark/jars/arc.jar \
--etl.config.uri=file://${ETL_CONF_BASE_URL}/job/dummy/testjob.json
```

**Comment by aarushissar** [comment]
Hi Mike,

Thanks for your patience and assistance. I managed to load records into the Kafka container via the Arc container. I was able to overcome this issue by adding the network and hostname properties to my docker run commands.

For others' benefit, I have included my docker run commands below.

docker run \
--network=host \
--hostname=127.0.0.1 \
-v $(pwd):${ETL_CONF_BASE_URL} \
-e "ETL_CONF_ENV=test" \
-e "ETL_CONF_BASE_URL=${ETL_CONF_BASE_URL}" \
-it -p 4040:4040 seddonm1/arc:1.0.8 \
bin/spark-submit \
--master local[*] \
--driver-memory=12G \
--driver-java-options="-XX:+UseG1GC -XX:-UseGCOverheadLimit -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap" \
--class au.com.agl.arc.ARC \
/opt/spark/jars/arc.jar \
--etl.config.uri=file://${ETL_CONF_BASE_URL}/job/dummy/testjob.json

**Comment by seddonm1** [comment]
Great.

FYI: I refactored the KafkaExtract yesterday to be multi-threaded and I'm planning on creating a KafkaCommitExecute stage so we will probably add a new key to KafkaExtract called `autoCommit` then we can use the KafkaCommitExecute to take the result set and automatically commit offsets back to Kafka/Zookeeper after you have done other work inside Arc (like maybe only do the commit after writing to Parquet).
