### ISSUE TITLE
JDBCLoad forces case-sensitive column definition

### ISSUE THREAD

**Issue by A142764** [AGLEnergy/arc#23]
Using latest ARC saw some failures of previously working code, root is the following protective code being a little too aggressive.

https://github.com/AGLEnergy/arc/blob/a613fb06d5abc6e77e9af2dc8121fb86b5a4e5d8/src/main/scala/au/com/agl/arc/load/JDBCLoad.scala#L173

**Comment by seddonm1** [comment]
Closed with commit: https://github.com/AGLEnergy/arc/commit/d1912558d96d26e4abedb57d8b73fa5fae3255d2
