### ISSUE TITLE
Suggestion: Metadata

### ISSUE THREAD

**Issue by aissar** [AGLEnergy/arc#3]
1. Add 'PII' indicator to schema file i.e. 0 or 1 to indicate whether a particular column contains personally identifiable information (PII)
2. Add 'Data Classification' attribute to schema file e.g. string describing the data classification of a particular data set 'Unclassified', 'Sensitive', etc.

Interested in the feasibility of this and your thoughts?

**Comment by seddonm1** [comment]
Hi.
Good idea.

Alternative idea we had a new key to each item called `metadata`. You would then be able to add any value you wanted. We could then add something like a `MetadataFilterTransform` to be able to automatically filter the dataset based on column metadata conditions? This metadata would then be attached to the column and persisted in Parquet etc.

For example we would move the `primaryKey` and `position` fields into it as they were a bit clumsy in the first place. 

```json
{
  "id" : "982cbf60-7ba7-4e50-a09b-d8624a5c49e6",
  "name" : "marketing_opt_in_flag",
  "description" : "Whether the customer has opted in to receive marketing communications.",
  "type" : "boolean",
  "trim" : true,
  "nullable" : true,
  "nullableValues" : [ "", "null" ],
  "trueValues" : [ "true", "TRUE", "t", "1" ],
  "falseValues" : [ "false", "FALSE", "f", "0" ],
  "metadata": {
    "primaryKey": false,
    "position": 2,
  }
}
```

**Comment by aissar** [comment]
Thanks Mike,

I like the proposed option you’ve outlined above. Will you let me know when it’s ready to test?

I’m planning on using this metadata to determine which columns can be pushed to the cloud or whether specific columns need to be tokenised first. The MetadataFilterTransform stage would assist with excluding potentially sensitive information in my case :)

**Comment by seddonm1** [comment]
@aissar I have just pushed the first (experimental) version of the metadata changes. It introduces the `MetadataFilterTransform` which allows you to filter out records from an `inputView` based on the evaluation of a SQL statement against the metadata associated with `inputView`. Currently the only stage which attaches `metadata` is the `TypingTransform` but that will improve.

You can see docs here:
https://aglenergy.github.io/arc/transform/#metadatafiltertransform

I have also released 1.0.8 so all dev will happen against 1.0.9 which is now in docker.

I have marked it experimental so please give feedback.

**Comment by aissar** [comment]
@seddonm1 , thank you for implementing this valuable feature. I've tested both approaches you've outlined in the documented examples and they work like a charm. I particularly like the second approach, which enables users to quickly make changes via the job SQL parameters rather than having to change the metadata itself or the SQL logic itself :)

**Comment by seddonm1** [comment]
@aissar Great. Please have a play and feel free to open a new issue. we are trying to build software that people can use so if you have any suggestions (even documentation) it would be good to hear (or a PR)
