### ISSUE TITLE
DatabricksSecretsDynamicConfigurationPlugin: parameter substitution errors

### ISSUE THREAD

**Issue by A142614** [AGLEnergy/arc#32]
when using config "au.com.agl.arc.plugins.config.DatabricksSecretsDynamicConfigurationPlugin"

parameter substitution for values which have either "=","*" or "." fails like “foo1://foo2/extract=12fo*.f003”

{"event":"exit","status":"failure","success":false,"duration":10938,"reason":{"messages":["String: 36: Could not resolve substitution to a value: ${INPUT_FILE_NAME}"],"stackTrace":

**Comment by A139834** [comment]
Resolved in `1.9.0` release:

https://github.com/AGLEnergy/arc/commit/2f9d8b687e640051e2a0cfebb984e6fbb1184f9f#diff-5bf50f4830cc631ed5dc2c01c8b68117R40
